[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "vscouter"
authors = [{name = "Vihaan Chhabria", email = "chhabria.vihaan2@gmail.com"}]
dynamic = ["version", "description"]
